DECLARE
    CURSOR CUR_DEPTS IS
    SELECT
        DEPARTMENT_ID,
        DEPARTMENT_NAME
    FROM
        DEPARTMENTS;
    V_DEPARTMENT_ID   DEPARTMENTS.DEPARTMENT_ID%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    OPEN CUR_DEPTS;
    LOOP
        FETCH CUR_DEPTS INTO V_DEPARTMENT_ID, V_DEPARTMENT_NAME;
        EXIT WHEN CUR_DEPTS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_DEPARTMENT_ID
                             ||' '
                             ||V_DEPARTMENT_NAME);
    END LOOP;

    CLOSE CUR_DEPTS;
END;
/